### PR TITLE
Problem: doc don't explain instantiate parameters

### PR DESCRIPTION
**Pull request by yihuang**
Solution:
- add section on that

An open question to consider: Should we allow third party to unsubscribe an expired subscription and receive the deposited tokens as reward, if the original subscriber forget to do that?

### CODE REVIEW

**Review by tomtau — APPROVED** [review]
> Should we allow third party to unsubscribe an expired subscription and receive the deposited tokens as reward, if the original subscriber forget to do that?

Who would receive the tokens -- the third party or the original subscriber?

**Comment by yihuang** [comment]
> > Should we allow third party to unsubscribe an expired subscription and receive the deposited tokens as reward, if the original subscriber forget to do that?
> 
> Who would receive the tokens -- the third party or the original subscriber?

third party, if we do this, then we'll need another cool down period after expiration, to avoid third party rob user's fund.

**Comment by yihuang** [comment]
https://github.community/t/feature-request-conditional-required-checks/16761/9
it seems conditional work flow don't work well with required checks ;(

**Comment by tomtau** [comment]
> third party, if we do this, then we'll need another cool down period after expiration, to prevent third party robbing user's fund immediately after expiration. which'll increase complexity a little bit though.

IMHO better to avoid that / keep it simple for now -- as there may be other real world requirements for more contract changes, having a simple base version first is preferable

**Pull request merged**
